\hypertarget{group__exceptions}{}\section{An execption-\/like library.}
\label{group__exceptions}\index{An execption-\/like library.@{An execption-\/like library.}}


An exception-\/like mechanism for C.  


Collaboration diagram for An execption-\/like library.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{group__exceptions}
\end{center}
\end{figure}
\subsection*{Modules}
\begin{DoxyCompactItemize}
\item 
\hyperlink{group__helpers}{Helpers for exceptions}
\begin{DoxyCompactList}\small\item\em These are some internal helpers, not part of the public A\+PI. \end{DoxyCompactList}\end{DoxyCompactItemize}
\subsection*{Data Structures}
\begin{DoxyCompactItemize}
\item 
struct \hyperlink{structexception__handler__frame}{exception\+\_\+handler\+\_\+frame}
\item 
struct \hyperlink{structexception__stack__frame}{exception\+\_\+stack\+\_\+frame}
\end{DoxyCompactItemize}
\subsection*{Macros}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{group__exceptions_gadf8cc03bd0ede7f3e5aafa57de5016dd}\label{group__exceptions_gadf8cc03bd0ede7f3e5aafa57de5016dd}} 
\#define {\bfseries \+\_\+\+\_\+concatenate\+\_\+tokens}(x,  y)~x \#\# y
\item 
\mbox{\Hypertarget{group__exceptions_ga0d2e02c74b05d3ff3bfa9eb3dcd891e3}\label{group__exceptions_ga0d2e02c74b05d3ff3bfa9eb3dcd891e3}} 
\#define {\bfseries \+\_\+\+\_\+conc}(z,  w)~\+\_\+\+\_\+concatenate\+\_\+tokens(z,w)
\end{DoxyCompactItemize}
\subsection*{Typedefs}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{group__exceptions_ga07c60bc46505779b049ce597fe609258}\label{group__exceptions_ga07c60bc46505779b049ce597fe609258}} 
typedef void($\ast$ {\bfseries exception\+\_\+handler}) (int)
\item 
\mbox{\Hypertarget{group__exceptions_ga644495f4913e96a83cdf2779fd813974}\label{group__exceptions_ga644495f4913e96a83cdf2779fd813974}} 
typedef struct \hyperlink{structexception__stack__frame}{exception\+\_\+stack\+\_\+frame} $\ast$$\ast$ {\bfseries exception\+\_\+context}
\end{DoxyCompactItemize}
\subsection*{Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{group__exceptions_ga7eda2653ee54e0c95e9d51b8fd873298}\label{group__exceptions_ga7eda2653ee54e0c95e9d51b8fd873298}} 
void {\bfseries raise\+\_\+exception} (\hyperlink{structexception__stack__frame}{exception\+\_\+context} context)
\item 
\mbox{\Hypertarget{group__exceptions_ga5232fee2c414c5ff1ff44dc28c83cf42}\label{group__exceptions_ga5232fee2c414c5ff1ff44dc28c83cf42}} 
void {\bfseries exception\+\_\+unwind} (\hyperlink{structexception__stack__frame}{exception\+\_\+context} context, int errcode)
\item 
\mbox{\Hypertarget{group__exceptions_gad0ebd2587ae85b044e1306a026246a27}\label{group__exceptions_gad0ebd2587ae85b044e1306a026246a27}} 
static void {\bfseries \+\_\+\+\_\+exc\+\_\+push\+\_\+frame} (\hyperlink{structexception__stack__frame}{exception\+\_\+context} context, struct \hyperlink{structexception__stack__frame}{exception\+\_\+stack\+\_\+frame} $\ast$frame)
\item 
\mbox{\Hypertarget{group__exceptions_ga47cfe7a060b16ac1cd9a4432853205dc}\label{group__exceptions_ga47cfe7a060b16ac1cd9a4432853205dc}} 
static struct \hyperlink{structexception__stack__frame}{exception\+\_\+stack\+\_\+frame} $\ast$ {\bfseries \+\_\+\+\_\+exc\+\_\+try} (\hyperlink{structexception__stack__frame}{exception\+\_\+context} context, int errcode)
\item 
\mbox{\Hypertarget{group__exceptions_ga9d85149bdb927245ff694068119412df}\label{group__exceptions_ga9d85149bdb927245ff694068119412df}} 
static struct \hyperlink{structexception__stack__frame}{exception\+\_\+stack\+\_\+frame} $\ast$ {\bfseries \+\_\+\+\_\+exc\+\_\+exit\+\_\+try} (\hyperlink{structexception__stack__frame}{exception\+\_\+context} context)
\end{DoxyCompactItemize}


\subsection{Detailed Description}
An exception-\/like mechanism for C. 

Exceptions are supported by many object-\/oriented languages, such as Java, C++ and Python, but not by C. This makes programming certain kinds of tasks somewhat complicated. These are tasks that can cause a thread to exit back through several layers of calls. For example, a system call may lead to a stack of nested calls to execute the code of a driver. If processing is to be rolled back to the point of entry to the kernel, all calls in that stack need to propagate the error. This makes coding tedious and error-\/prone.

In C, there is a standard-\/library facility that can be used to implement such functionality, available by including {\ttfamily $<$setjmp.\+h$>$}. The help is in the form of functions {\ttfamily setjmp()} and {\ttfamily longjmp} (and their vatiatons). In this library, these standard calls, wrapped by some suitable macros, and using some G\+NU G\+CC extensions (nested functions), provide some easy-\/to-\/use exception-\/like programming structures.

\subsubsection*{Examples}

Before we describe the details, we show some examples of the library\textquotesingle{}s use.

A try-\/block is declared as follows\+: 
\begin{DoxyCode}
TRY\_WITH(context) \{

    ON\_ERROR \{
        printf(\textcolor{stringliteral}{"Error in what I was doing\(\backslash\)n"});
        \textcolor{comment}{// After this, execute the finally }
    \}

    FINALLY(e) \{
        \textcolor{keywordflow}{if}(e) 
            printf(\textcolor{stringliteral}{"Continuing after error\(\backslash\)n"});         
        \textcolor{keywordflow}{else}
            printf(\textcolor{stringliteral}{"Finished without error\(\backslash\)n"});
    \}

    \textcolor{comment}{// do something here }
    \textcolor{keywordflow}{if}(error\_happens)
        raise\_exception(context);

    \textcolor{comment}{// or call a function that may call raise\_exception()}
    do\_something\_else();

    \textcolor{comment}{// If we leave here, FINALLY will be executed }
\}
\end{DoxyCode}


For example, one could do the following, to construct a composite resource\+: 
\begin{DoxyCode}
Resource r1, r2, r3;
TRY\_WITH(context) \{
    lock\_monitor();
    FINALLY(e) \{
        unlock\_monitor();
    \}

    \textcolor{comment}{// This may raise\_exception(...)}
    r1 = acquire\_resource1();
    ON\_ERROR \{
        release\_resource1(r1);
    \}

    \textcolor{comment}{// This may raise\_exception(...)}
    r2 = acquire\_resource2(r2);

    ON\_ERROR \{
        release\_resource2(r2);
    \}
    
    \textcolor{comment}{// This may raise\_exception(...)}
    r3 = acquire\_resrouce3(r1, r2);
\}
\textcolor{keywordflow}{return} r3;
\end{DoxyCode}


\subsubsection*{How it works}

The workings are based on the idea of an {\bfseries exception stack}. The elements of this stack are called {\bfseries exception stack frames} (E\+S\+Fs). Each thread should have its own exception stack. When a T\+R\+Y\+\_\+\+W\+I\+TH(...) block begins, a new E\+SF is pushed to the stack, and the block starts to execute.

Each E\+SF has two lists of functions of type @ exception\+\_\+handler, which is defined as {\ttfamily void ($\ast$)(int)}. The nodes for these lists are {\ttfamily struct \hyperlink{structexception__handler__frame}{exception\+\_\+handler\+\_\+frame}} objects. Initially, the new E\+SF has empty lists. The first list is the list of {\bfseries catchers} and the second is the list of {\bfseries finalizers}.

As the T\+R\+Y-\/block executes, execution reaches {\ttfamily F\+I\+N\+A\+L\+L\+Y()} and {\ttfamily O\+N\+\_\+\+E\+R\+R\+OR} blocks. When a {\ttfamily F\+I\+N\+A\+L\+L\+Y()} block is reached, a new handler is added to the finalizers list. When a {\ttfamily O\+N\+\_\+\+E\+R\+R\+OR} block is reached, a new handler is added to the catchers list.

If execution arrives at the end of the T\+R\+Y-\/block, the list of catchers is thrown away and the finalizers are executed (in reverse order, that is, last-\/in-\/first-\/out).

If at some point the function {\ttfamily raise\+\_\+exception()} is called, execution jumps back at the T\+R\+Y-\/block at the top of the exception stack. There, each catcher is first executed, followed by all the finalizers. At the end, the E\+SF is popped from the exception stack. Then, if at least one catcher did execute, the exception is considered handled, and execution continues after the T\+R\+Y-\/block. If however there was no catcher executed, and the exception stack is non-\/empty, then {\ttfamily raise\+\_\+exception()} is called again, to repeat the process.

An exception stack is defined simply as a pointer to {\ttfamily struct \hyperlink{structexception__stack__frame}{exception\+\_\+stack\+\_\+frame}}. An \+\_\+\+\_\+exception context\+\_\+\+\_\+is a pointer to such a pointer, that is, 
\begin{DoxyCode}
\textcolor{keyword}{typedef} \textcolor{keyword}{struct }\hyperlink{structexception__stack__frame}{exception\_stack\_frame}** exception\_context;
\end{DoxyCode}
 A context needs to be available to our code in two places\+: when a {\ttfamily T\+R\+Y\+\_\+\+W\+I\+T\+H(context)} block is defined, and when {\ttfamily raise\+\_\+exception(context)} is called.

One can simply define a context as a global variable\+: 
\begin{DoxyCode}
\textcolor{comment}{// at top level}
\textcolor{keyword}{struct }execution\_stack\_frame* exception\_stack = NULL;
\textcolor{preprocessor}{#define TRY  TRY\_WITH(&exception\_stack)}
\textcolor{preprocessor}{#define RAISE  raise\_exception(&exception\_stack)}

TRY \{
    ...
    RAISE;
    ...
\}
\end{DoxyCode}


In a multi-\/threaded case, it is necessary to declare one context for each thread. This can be done at the T\+CB, for example.


\begin{DoxyCode}
\textcolor{keyword}{struct }\hyperlink{structthread__control__block}{TCB} \{
    ....
    \textcolor{keyword}{struct }execution\_stack\_frame* exception\_stack = NULL;   
\}

\textcolor{preprocessor}{#define TRY  TRY\_WITH(& CURTHREAD->exception\_stack)}
\textcolor{preprocessor}{#define RAISE  raise\_exception(& CURTHREAD->exception\_stack)}
\end{DoxyCode}


\subsubsection*{Performance}

Although setting up a T\+R\+Y-\/block is relatively cheap (basically, a call to {\ttfamily setjmp} is done), it is better to avoid calling exception handlers. So, for very critical pieces of code, one could do 
\begin{DoxyCode}
TRY \{
    lock\_mutex();
    ON\_ERROR \{
        unlock\_mutex();
    \}

    ... \textcolor{comment}{// stuff}

    unlock\_mutex();
\}
\end{DoxyCode}
 instead of the more convenient 
\begin{DoxyCode}
TRY \{
    lock\_mutex();
    FINALLY(e) \{
        unlock\_mutex();
    \}

    ... \textcolor{comment}{// stuff    }
\}
\end{DoxyCode}


The first case is faster, because it avoids a function call, when there is no exception, whereas the second will make a call to the {\ttfamily F\+I\+N\+A\+L\+LY} block, even without an exception raised. But, remember\+: {\bfseries premature optimization is the source of all evil}.

\subsubsection*{Raising from inside an exception handler}

It is perfecly legal and supported to have exceptions raised from inside {\ttfamily O\+N\+\_\+\+E\+R\+R\+OR} or {\ttfamily F\+I\+N\+A\+L\+LY} blocks (or the functions they call).

What happens in this case is that the exception handler execution is aborted and the processing continues with the next exception handler of the E\+SF. 